### ISSUE TITLE
Added Frontend Documentation

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Documentation-Khazana#1]
Added Frontend Documentation,
Full Roadmap of Frontend
Don`t Copy Paste from Google and Blogs, You can Take it for Reference only, Modified it, and Start Contributing

**Comment by siddhi-244** [comment]
Can I work on it ?

**Comment by Ayush7614** [comment]
Go Ahead

**Comment by Emritik** [comment]
Can you assign this issue to me

**Comment by Ayush7614** [comment]
> Can you assign this issue to me

Look on Other Issues @Emritik Siddhi asked First for This Issue

**Comment by Emritik** [comment]
Okay no problem

**Comment by Ayush7614** [comment]
Closed Via #16
