### ISSUE TITLE
Add documentation of Data Structures & Algorithms for Interviews

### ISSUE THREAD

**Issue by utkarsh006** [Ayush7614/Documentation-Khazana#19]
- Hey Admin ! I want to add the documentation for the above topic.
- This topic is widely asked by the folks and is quite important to them.
- Assign me the issue under hacktoberfest.

**Comment by Ayush7614** [comment]
Go Ahead

**Comment by utkarsh006** [comment]
@Ayush7614 Kindly give label as hacktoberfest only. Hacktoberfest accepted is given to PR's.
